---
- name: Build dependencies
  apt: pkg=nginx state=build-dep

- name: Build
  shell: 'yes | dpkg-buildpackage -b'
  register: dpkg_bp_cmd
  args:
    chdir: '{{ nginx_src_build_path }}/nginx-{{ nginx_src_version }}'
