---

- name: Add nginx APT key
  apt_key:
    url: 'http://nginx.org/keys/nginx_signing.key'
    state: present
  register: apt_repo_res
  retries: 2
  until: apt_repo_res|success

- name: Ensure APT official nginx repository (mainline)
  apt_repository:
    repo: >-
      {{ nginx_mainline_deb }}/{{ ansible_distribution|lower }}/
      {{ ansible_distribution_release }} nginx
    update_cache: true

- name: Ensure APT official nginx repository src (mainline)
  apt_repository:
    repo: >-
      {{ nginx_mainline_src }}/{{ ansible_distribution|lower }}/
      {{ ansible_distribution_release }} nginx
    update_cache: true

- name: Install deps
  apt:
    name: '{{ _nginx_src_deps + nginx_src_deps }}'
    state: present
  register: apt_deps_res
  retries: 2
  until: apt_deps_res|success

- name: Create build directory
  file:
    path: '{{ nginx_src_build_path }}'
    state: directory
    owner: _apt
    group: root
    mode: 0775

- name: Create build modules directories
  file:
    path: '{{ nginx_src_build_path }}/{{ item.name }}'
    state: directory
    owner: _apt
    group: root
    mode: 0775
  with_items: '{{ nginx_src_modules }}'

- name: Create build modules libs directories (if any)
  file:
    path: '{{ nginx_src_build_path }}/{{ item.name }}'
    state: directory
    owner: _apt
    group: root
    mode: 0775
  with_items: '{{ nginx_src_libs }}'

- name: Create build modules deps directories (if any)
  file:
    path: '{{ nginx_src_build_path }}/{{ item.0.name }}/{{ item.1.name }}'
    state: directory
    owner: _apt
    group: root
    mode: 0775
  with_subelements:
    - '{{ nginx_src_modules }}'
    - deps
    - skip_missing: true

- name: Install nginx sources
  command: 'apt source nginx={{ nginx_src_version }}'
  register: apt_src_cmd
  changed_when: apt_src_cmd.stdout.find('already downloaded file') < 0
  environment:
    LC_ALL: 'en_US.UTF-8'
  args:
    chdir: '{{ nginx_src_build_path }}'
