---

- name: List folders
  shell: ls -al {{ nginx_src_build_path }}/

- name: Install nginx package
  apt:
    deb: '{{ nginx_src_build_path }}/nginx_{{ nginx_src_version }}-1~{{ ansible_distribution_release }}_amd64.deb'
    force: true

- name: Hold installed nginx
  dpkg_selections:
    name: nginx
    selection: hold

- name: Install modules
  copy:
    src: '{{ nginx_dir }}/objs/{{ item.name }}.so'
    dest: '/etc/nginx/modules/'
    remote_src: true
  when: item.dynamic|default(false)
  with_items: '{{ nginx_src_modules }}'
