---

- import_tasks: check.yml

- import_tasks: deps.yml
  when: _nginx_src_changed

- import_tasks: modules.yml
  when: _nginx_src_changed

- import_tasks: build.yml
  when: _nginx_src_changed

- import_tasks: install.yml
  when: _nginx_src_changed

- import_tasks: cleanup.yml
  when: _nginx_src_changed and nginx_src_cleanup|default(false)
