---
- name: Download modules
  unarchive: src="{{ item.url }}" dest='{{ nginx_src_build_path}}/{{  item.name }}' remote_src=yes extra_opts='--strip-components=1'
  with_items: "{{ nginx_src_modules }}"

- name: Download modules deps (if any)
  unarchive: src="{{ item.1.url }}" dest='{{ nginx_src_build_path }}/{{ item.0.name }}/{{ item.1.name }}' remote_src=yes extra_opts='--strip-components=1'
  with_subelements:
    - "{{ nginx_src_modules }}"
    - deps
    - skip_missing: true

- name: Modify debian rules to build with modules
  lineinfile:
    path: '{{ nginx_src_build_path }}/nginx-{{ nginx_src_version }}/debian/rules'
    regexp: 'CFLAGS(.+)stream_ssl_preread_module \-\-with-cc-opt(.+)"$'
    line: 'CFLAGS\1stream_ssl_preread_module {{ _nginx_src_args }} --with-cc-opt\2"'
    backrefs: yes

- name: Modify debian rules to build with modules
  lineinfile:
    path: '{{ nginx_src_build_path }}/nginx-{{ nginx_src_version }}/debian/rules'
    regexp: 'CFLAGS(.+)stream_ssl_preread_module \-\-with-cc-opt(.+)debug$'
    line: 'CFLAGS\1stream_ssl_preread_module {{ _nginx_src_args }} --with-cc-opt\2debug'
    backrefs: yes
