---

- name: Download modules
  unarchive:
    src: '{{ item.url }}'
    dest: '{{ nginx_src_build_path }}/{{ item.name }}'
    remote_src: true
    extra_opts: '--strip-components=1'
  with_items: '{{ nginx_src_modules }}'

- name: Download modules libs (if any)
  unarchive:
    src: '{{ item.url }}'
    dest: '{{ nginx_src_build_path }}/{{ item.name }}'
    remote_src: true
    extra_opts: '--strip-components=1'
  with_items: '{{ nginx_src_libs }}'

- name: Download modules deps (if any)
  unarchive:
    src: '{{ item.1.url }}'
    dest: '{{ nginx_src_build_path }}/{{ item.0.name }}/{{ item.1.name }}'
    remote_src: true
    extra_opts: '--strip-components=1'
  with_subelements:
    - '{{ nginx_src_modules }}'
    - deps
    - skip_missing: true

- name: Modify debian rules to build with modules
  replace:
    path: '{{ nginx_dir }}/debian/rules'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - regexp: '\.\/configure(.+?)\-\-prefix'
      replace: './configure {{ _nginx_src_args }} --prefix'
    - regexp: '\-\-with-cc\-opt="([^\$]+?)?\$'
      replace: '--with-cc-opt="{{ nginx_src_cc_opt }} $'
    - regexp: '\-\-with-ld\-opt="([^\$]+?)?\$'
      replace: '--with-ld-opt="{{ nginx_src_ld_opt }} $'

- name: Modify debian rules to cleanup build folders
  lineinfile:
    path: '{{ nginx_dir }}/debian/rules'
    regexp: '(.+?)rm \-r?f \$\(CURDIR\)\/objs$'
    line: '\1rm -rf $(CURDIR)/objs'
    backrefs: true

- name: Modify debian rules to ignore dh_shlibdeps
  lineinfile:
    path: '{{ nginx_dir }}/debian/rules'
    regexp: '(.+?)dh_shlibdeps \-a(.+)?$'
    line: '\1dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info'
    backrefs: true
