---
- name: Download modules
  unarchive: src="{{ item.url }}" dest='{{ nginx_src_build_path}}/{{  item.name }}' remote_src=yes extra_opts='--strip-components=1'
  with_items: "{{ nginx_src_modules }}"

- name: Download modules deps (if any)
  unarchive: src="{{ item.1.url }}" dest='{{ nginx_src_build_path }}/{{ item.0.name }}/{{ item.1.name }}' remote_src=yes extra_opts='--strip-components=1'
  with_subelements:
    - "{{ nginx_src_modules }}"
    - deps
    - skip_missing: true

- name: Modify debian rules to build with modules
  lineinfile:
    path: '{{ nginx_src_build_path }}/nginx-{{ nginx_src_version }}/debian/rules'
    regexp: 'CFLAGS="(.*?)"(.+)stream_ssl_preread_module(.+?)\-\-with\-cc\-opt(.+)"$'
    line: 'CFLAGS="{{ nginx_src_cflags }}"\2stream_ssl_preread_module {{ _nginx_src_args }} --with-cc-opt\4"'
    backrefs: yes
  register: deb_rules_register

- name: Modify debian rules to build with modules
  lineinfile:
    path: '{{ nginx_src_build_path }}/nginx-{{ nginx_src_version }}/debian/rules'
    regexp: 'CFLAGS="(.*?)"(.+)stream_ssl_preread_module(.+?)\-\-with\-cc\-opt(.+)debug$'
    line: 'CFLAGS="{{ nginx_src_cflags}}"\2stream_ssl_preread_module {{ _nginx_src_args }} --with-cc-opt\4debug'
    backrefs: yes
